# Dockerfile

# base image
FROM node:20-alpine
WORKDIR /usr/src

COPY package*.json ./
RUN npm ci

COPY . .

# Build-time vars needed for static generation/prefetch
ARG SUPPLEMENTAL_SOLR
ARG SOLR_USER
ARG SOLR_PASS
ARG USE_STATIC_PROPS_CACHE=0
ARG SOLR_MAX_CONCURRENCY=3
ARG SOLR_HTTP_RETRIES=1
ENV SUPPLEMENTAL_SOLR=$SUPPLEMENTAL_SOLR
ENV SOLR_USER=$SOLR_USER
ENV SOLR_PASS=$SOLR_PASS
ENV USE_STATIC_PROPS_CACHE=$USE_STATIC_PROPS_CACHE

RUN SOLR_MAX_CONCURRENCY=$SOLR_MAX_CONCURRENCY SOLR_HTTP_RETRIES=$SOLR_HTTP_RETRIES npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
